// <auto-generated />
using Catalogo.Persistencia.BaseDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalogo.Persistencia.BaseDatos.Migrations
{
    [DbContext(typeof(AplicationBDContext))]
    [Migration("20200911064711_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalogo")
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalogo.Dominio.Producto", b =>
                {
                    b.Property<int>("SKU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("SKU");

                    b.HasIndex("SKU");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            SKU = 19806,
                            Existencia = 300,
                            Nombre = "PP-10|CARRETILLA DOBLE LLANTA,MGOS/MAD 2,10FT",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 31417,
                            Existencia = 300,
                            Nombre = "TRS-5F-GR|PALA PARA CANERIAS 5",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 74609,
                            Existencia = 300,
                            Nombre = "ET-CB-EP-30 ETIQUETA CODIGO DE BARRAS",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 74632,
                            Existencia = 300,
                            Nombre = "ET-CB-R-16MF ETIQUETA CODIGO DE BARRAS",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 74633,
                            Existencia = 300,
                            Nombre = "ET-CB-R8M-KID ETIQUETA CODIGO DE BARRAS",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 74639,
                            Existencia = 300,
                            Nombre = "ET-CB-MARTE-TP-M",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 86632,
                            Existencia = 300,
                            Nombre = "ENSAMBLE DE TARIMA Y CONTENEDOR MADERA",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 86714,
                            Existencia = 300,
                            Nombre = "SUBENSAMBLE TUBO-SOLERA R-4 FOR",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 86910,
                            Existencia = 300,
                            Nombre = "TARIMA DE 1.0X 1.2 HOME DEPOT",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 87010,
                            Existencia = 300,
                            Nombre = "DISPLAY-36-PRL-E-LW/36-R16AM-E-LW S/PROD",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 88836,
                            Existencia = 300,
                            Nombre = "TARIMA P/CARRETILLA CAT-KID",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 88980,
                            Existencia = 300,
                            Nombre = "TARIMA PARA CONTENEDOR #1 Y #2 DE EXHIBI",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 89177,
                            Existencia = 300,
                            Nombre = "TARIMA PARA CAT KID",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 89509,
                            Existencia = 300,
                            Nombre = "BOLSA TORNILLOS|BOLSA TORN. CAT-KIT TUB.",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 907855,
                            Existencia = 300,
                            Nombre = "R274-SME-10X-2|TUERCA HEXAGONAL M14 (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 910606,
                            Existencia = 300,
                            Nombre = "R22-TAPI-13|BARRA SOPORTE MOTOR IZQUIERDA (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 910607,
                            Existencia = 300,
                            Nombre = "R23-TAPI-13|TORNILLO HEXAGONAL M8X40MM (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 910608,
                            Existencia = 300,
                            Nombre = "R24-TAPI-13|RONDANA PLANA Ø8 (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 910609,
                            Existencia = 300,
                            Nombre = "R25-TAPI-13|MONTURA MOTOR (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 910610,
                            Existencia = 300,
                            Nombre = "R26-TAPI-13|RONDANA PLANA Ø12 (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 910611,
                            Existencia = 300,
                            Nombre = "R27-TAPI-13|RONDANA DE PRESION Ø12 (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 910612,
                            Existencia = 300,
                            Nombre = "R28-TAPI-13|TUERCA HEXAGONAL M12 (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 910613,
                            Existencia = 300,
                            Nombre = "R29.1-TAPI-13|VENTLADOR (PLASTICO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 910614,
                            Existencia = 300,
                            Nombre = "R29.2-TAPI-13|CAJA DEL CAPACITOR (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 910615,
                            Existencia = 300,
                            Nombre = "R29.3-TAPI-13|RONDANA PLANA Ø4 (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 910616,
                            Existencia = 300,
                            Nombre = "R29.4-TAPI-13|TORNILLO PAN M4X6MM  (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911925,
                            Existencia = 300,
                            Nombre = "R81-CEP-13|BALERO DE BOLAS 6203 (ACERO-PLASTICO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911926,
                            Existencia = 300,
                            Nombre = "R82-CEP-13|ARMAZON SUPERIOR (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911927,
                            Existencia = 300,
                            Nombre = "R82.2-CEP-13|RONDANA DENTADA   Ø4 (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911928,
                            Existencia = 300,
                            Nombre = "R83-CEP-13|OPRESOR DE CABLE (PLASTICO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911929,
                            Existencia = 300,
                            Nombre = "R83.1-CEP-13|TORNILLO PAN M4X14MM (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911930,
                            Existencia = 300,
                            Nombre = "R84-CEP-13|RONDANA PLANA Ø4 (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911931,
                            Existencia = 300,
                            Nombre = "R85-CEP-13|DEFLECTOR DE ASERRIN (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911932,
                            Existencia = 300,
                            Nombre = "R85.1-CEP-13|TORNILLO PAN M4X8MM (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911933,
                            Existencia = 300,
                            Nombre = "R86-CEP-13|TUERCA HEXAGONAL M20 (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911934,
                            Existencia = 300,
                            Nombre = "R87-CEP-13|SOPORTE DERECHO (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911935,
                            Existencia = 300,
                            Nombre = "R88-CEP-13|RESORTE (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911936,
                            Existencia = 300,
                            Nombre = "R89-CEP-13|FRENO DE SEGURIDAD (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911937,
                            Existencia = 300,
                            Nombre = "R90-CEP-13|TORNILLO ALLEN M5X12MM (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911938,
                            Existencia = 300,
                            Nombre = "R91-CEP-13|PLACA DE CONEXION (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911939,
                            Existencia = 300,
                            Nombre = "R92-CEP-13|RONDANA PLANA Ø8 (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 911940,
                            Existencia = 300,
                            Nombre = "R93-CEP-13|TORNILLO HEXAGONAL M8X16MM (ACERO)",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 999965,
                            Existencia = 300,
                            Nombre = "LJ-NS-278|LJ-NS-278",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 999971,
                            Existencia = 300,
                            Nombre = "LJ-NS-285|LJ-NS-285",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 999972,
                            Existencia = 300,
                            Nombre = "LJ-NS-286|LJ-NS-286",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 999973,
                            Existencia = 300,
                            Nombre = "LJ-NS-287|LJ-NS-287",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 999975,
                            Existencia = 300,
                            Nombre = "LJ-NS-289|LJ-NS-289",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 999976,
                            Existencia = 300,
                            Nombre = "LJ-NS-290|LJ-NS-290",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 999977,
                            Existencia = 300,
                            Nombre = "LJ-NS-291|LJ-NS-291",
                            Precio = 100.0
                        },
                        new
                        {
                            SKU = 999979,
                            Existencia = 300,
                            Nombre = "LJ-NS-293|LJ-NS-293",
                            Precio = 100.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
